accountapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accountapp import views

app_name = 'accountapp'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

panicTodo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('todos/', include('todoapp.urls')),

    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

todoapp/urls.py
from django.urls import path

from todoapp import views

app_name = 'todoapp'

urlpatterns = [
    path('', views.TodoListView.as_view(), name='todo'),
    path('todo-checking/<int:id>/', views.todo_checking, name='todo_checking'),
]

accountapp/models.py
from django.db import models

notiapp/models.py
from django.db import models


class Noti(models.Model):
    message = models.CharField(max_length=100)

todoapp/models.py
from django.db import models
from django.utils import timezone


class Todo(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    done = models.BooleanField(default=False)
    panic_time = models.DateTimeField(null=True)
    panic_description = models.TextField(null=True)

    def panic(self):
        if self.panic_time and timezone.now() >= self.panic_time:
            return self.panic_description
        return None

    def __str__(self):
        return self.title

accountapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

accountapp/views.py
from django.views.generic import TemplateView

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from accountapp.forms import UserForm


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('home')
    else:
        form = UserForm()
    return render(request, 'accountapp/signup.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('home')

notiapp/views.py
from django.shortcuts import render

# Create your views here.

todoapp/views.py
from celery import shared_task
from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import ListView

from todoapp.models import Todo


def todo_checking(request):
    try:
        check = Todo.objects.get(id=id)
        check.done = not check.done
        check.save()
        return HttpResponse("Todo status toggled successfully.")
    except Todo.DoesNotExist:
        return HttpResponse("Todo with the provided ID does not exist.")


class TodoListView(ListView):
    model = Todo
    context_object_name = 'todo_list'
    template_name = 'todoapp/todo_list.html'


@shared_task
def check_panic_time_and_send_notification():
    todos = Todo.objects.all()
    for todo in todos:
        if todo.panic_time <= timezone.now():
            send_panic_notification(todo)


def send_panic_notification(todo):
    # 이메일이나 다른 방법으로 알림을 보냅니다.
    pass

accountapp/templates/accountapp/signup.html
{% extends "base.html" %}

{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'accountapp:signup' %}">
        {% csrf_token %}
        {% include "accountapp/form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/base.html
<!-- templates/base.html -->
 <!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
 <html lang="en">
<head>
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<meta charset="utf-8">
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title> </head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <body>
            <main> {% block content %} {% endblock %} </main>
            <a href="https://www.flaticon.com/kr/free-icons/" title="괴물 아이콘">괴물 아이콘  제작자: Smash icons - Flaticon</a>
        </body>
    <script type="text/javascript">
        {% block js %}
        {% endblock %}
    </script>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}
 {% block title %}Home{% endblock %}
 {% block content %}
     {% if user.is_authenticated %} <div class="badge bg-primary text-wrap fs-6" style="width: 6rem;">Hi {{ user.username }}!</div>
     <a href="{% url 'accountapp:logout' %}">logout</a>
     <div class="container text-center">
        <h1>wellcome Panic Todo!</h1>
        {% else %}
          <p>You are not logged in</p>
          <a href="{% url 'accountapp:login' %}">Log In</a>
          <a href="{% url 'accountapp:signup' %}">Sign Up</a>
        {% endif %}
     </div>
{% endblock %}

todoapp/templates/todoapp/todo_list.html
{% extends 'base.html' %}
 {% block title %}Todo{% endblock %}
 {% block content %}
     <div class="container">
        {% if object_list %}
            <section class="vh-100" style="background-color: #eee; border-radius: .5rem .5rem 0 0;">
  <div class="row d-flex justify-content-center py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-9">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <h4 class="text-center my-3 pb-3">To Do App</h4>

            <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
              <div class="col-12">
                <div class="form-outline">
                  <input type="text" id="form1" class="form-control" />
                  <label class="form-label" for="form1">Enter a task here</label>
                </div>
              </div>



              <div class="col-12">
                <button type="submit" class="btn btn-primary">Save</button>
              </div>

              <div class="col-12">
                <button type="submit" class="btn btn-warning">Get tasks</button>
              </div>
            </form>

            <table class="table mb-4">
              <thead>
                <tr>
                  <th scope="col">No.</th>
                  <th scope="col">Todo item</th>
                  <th scope="col">Status</th>
                  <th scope="col">description</th>
                  <th scope="col">panic_description</th>
                  <th scope="col">panic_time</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
              {% for todo in todo_list %}
                <tr>
                  <th scope="row">{{ todo.id }}</th>
                  <td>{{ todo.title }}</td>
                  <td>{{ todo.done }}</td>
                  <td>{{ todo.description }}</td>
                  <td>{{ todo.panic_description }}</td>
                  <td>{{ todo.panic_time }}</td>
                  <td>
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <label>
                        <input data-id="{{ todo.id }}" type="checkbox" class="form-check-input" {% if todo.done %} checked {% endif %} >
                    </label>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>


          </div>
        </div>
      </div>
    </div>
  </div>
</section>
        {% else %}
            <h1>Not todo yet!</h1>
        {% endif %}
     </div>
     <pre id='result'></pre>
 {% endblock %}
{% block js %}
    $(document).ready(function(){
    $(".form-check-input").click(function(){
        var todoId = this.getAttribute("data-id");
        $.ajax({
            url: "/todos/todo-checking/" + todoId + "/",  // todo_checking 뷰 함수에 대한 URL
            type: "GET",
            success: function(response){
                console.log("Todo status toggled successfully!");
                // 성공적으로 처리되었을 때 추가적인 동작을 수행할 수 있음
            },
            error: function(xhr, status, error) {
                console.error("An error occurred while toggling todo status.");
            }
        });
    });
});

{% endblock %}